[platformio]
description = motion detection client for ESP32 with OLED display
default_envs = esp32dev

[env]
monitor_speed = 115200
framework = arduino
lib_deps =
    sui77/rc-switch@^2.6.4
    adafruit/Adafruit GFX Library@^1.11.9
	https://github.com/nhatuan84/esp32-sh1106-oled

[env:esp32dev]
platform = espressif32
board = esp32dev
upload_speed = 921600 # uncomment if you have issues with uploading

[env:nano]
platform = atmelavr
board = nanoatmega328new