[platformio]
description = fading led example
default_envs = esp32dev

[env]
monitor_speed = 115200
framework = arduino

[env:esp32dev]
platform = espressif32
board = esp32dev
upload_speed = 921600 # uncomment if you have issues with uploading